version: "3.7"

services:
  hashiplayero:
    image: hashiplayero1:github
    container_name: hashiplayero
    networks:
      - caddy
    ports:
      - 8080:8080
    environment:
      url: https://hashiplayero.pl
    labels:
      caddy: hashiplayero.pl www.hashiplayero.pl
      caddy.reverse_proxy: "{{upstreams 8080}}"

  caddy:
    image: lucaslorentz/caddy-docker-proxy:ci-alpine
    restart: unless-stopped
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    environment:
      - CADDY_INGRESS_NETWORKS=caddy
    networks:
      - caddy
    volumes:      
      - /var/run/docker.sock:/var/run/docker.sock
      - caddy_data:/data

networks:
  caddy:
    external: true

volumes:
  caddy_data: {}
